// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TabularRLData.proto

#include "TabularRLData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace mancala {
constexpr QAgent::QAgent(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : q_()
  , npits_(0)
  , nseeds_(0){}
struct QAgentDefaultTypeInternal {
  constexpr QAgentDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~QAgentDefaultTypeInternal() {}
  union {
    QAgent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT QAgentDefaultTypeInternal _QAgent_default_instance_;
}  // namespace mancala
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_TabularRLData_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_TabularRLData_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_TabularRLData_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_TabularRLData_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mancala::QAgent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mancala::QAgent, npits_),
  PROTOBUF_FIELD_OFFSET(::mancala::QAgent, nseeds_),
  PROTOBUF_FIELD_OFFSET(::mancala::QAgent, q_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::mancala::QAgent)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mancala::_QAgent_default_instance_),
};

const char descriptor_table_protodef_TabularRLData_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023TabularRLData.proto\022\007mancala\"2\n\006QAgent"
  "\022\r\n\005npits\030\001 \001(\005\022\016\n\006nseeds\030\002 \001(\005\022\t\n\001Q\030\003 \003"
  "(\002b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_TabularRLData_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TabularRLData_2eproto = {
  false, false, 90, descriptor_table_protodef_TabularRLData_2eproto, "TabularRLData.proto", 
  &descriptor_table_TabularRLData_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_TabularRLData_2eproto::offsets,
  file_level_metadata_TabularRLData_2eproto, file_level_enum_descriptors_TabularRLData_2eproto, file_level_service_descriptors_TabularRLData_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_TabularRLData_2eproto_getter() {
  return &descriptor_table_TabularRLData_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_TabularRLData_2eproto(&descriptor_table_TabularRLData_2eproto);
namespace mancala {

// ===================================================================

class QAgent::_Internal {
 public:
};

QAgent::QAgent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  q_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:mancala.QAgent)
}
QAgent::QAgent(const QAgent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      q_(from.q_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&npits_, &from.npits_,
    static_cast<size_t>(reinterpret_cast<char*>(&nseeds_) -
    reinterpret_cast<char*>(&npits_)) + sizeof(nseeds_));
  // @@protoc_insertion_point(copy_constructor:mancala.QAgent)
}

inline void QAgent::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&npits_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&nseeds_) -
    reinterpret_cast<char*>(&npits_)) + sizeof(nseeds_));
}

QAgent::~QAgent() {
  // @@protoc_insertion_point(destructor:mancala.QAgent)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void QAgent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void QAgent::ArenaDtor(void* object) {
  QAgent* _this = reinterpret_cast< QAgent* >(object);
  (void)_this;
}
void QAgent::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void QAgent::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void QAgent::Clear() {
// @@protoc_insertion_point(message_clear_start:mancala.QAgent)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  q_.Clear();
  ::memset(&npits_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nseeds_) -
      reinterpret_cast<char*>(&npits_)) + sizeof(nseeds_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* QAgent::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 npits = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          npits_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 nseeds = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          nseeds_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated float Q = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_q(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29) {
          _internal_add_q(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* QAgent::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mancala.QAgent)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 npits = 1;
  if (this->_internal_npits() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_npits(), target);
  }

  // int32 nseeds = 2;
  if (this->_internal_nseeds() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_nseeds(), target);
  }

  // repeated float Q = 3;
  if (this->_internal_q_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_q(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mancala.QAgent)
  return target;
}

size_t QAgent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mancala.QAgent)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float Q = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_q_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    total_size += data_size;
  }

  // int32 npits = 1;
  if (this->_internal_npits() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_npits());
  }

  // int32 nseeds = 2;
  if (this->_internal_nseeds() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nseeds());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData QAgent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    QAgent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*QAgent::GetClassData() const { return &_class_data_; }

void QAgent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<QAgent *>(to)->MergeFrom(
      static_cast<const QAgent &>(from));
}


void QAgent::MergeFrom(const QAgent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mancala.QAgent)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  q_.MergeFrom(from.q_);
  if (from._internal_npits() != 0) {
    _internal_set_npits(from._internal_npits());
  }
  if (from._internal_nseeds() != 0) {
    _internal_set_nseeds(from._internal_nseeds());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void QAgent::CopyFrom(const QAgent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mancala.QAgent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QAgent::IsInitialized() const {
  return true;
}

void QAgent::InternalSwap(QAgent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  q_.InternalSwap(&other->q_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(QAgent, nseeds_)
      + sizeof(QAgent::nseeds_)
      - PROTOBUF_FIELD_OFFSET(QAgent, npits_)>(
          reinterpret_cast<char*>(&npits_),
          reinterpret_cast<char*>(&other->npits_));
}

::PROTOBUF_NAMESPACE_ID::Metadata QAgent::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TabularRLData_2eproto_getter, &descriptor_table_TabularRLData_2eproto_once,
      file_level_metadata_TabularRLData_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mancala
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mancala::QAgent* Arena::CreateMaybeMessage< ::mancala::QAgent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mancala::QAgent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
