# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TabularRLData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TabularRLData.proto',
  package='mancala',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13TabularRLData.proto\x12\x07mancala\"2\n\x06QAgent\x12\r\n\x05npits\x18\x01 \x01(\x05\x12\x0e\n\x06nseeds\x18\x02 \x01(\x05\x12\t\n\x01Q\x18\x03 \x03(\x02\x62\x06proto3'
)




_QAGENT = _descriptor.Descriptor(
  name='QAgent',
  full_name='mancala.QAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='npits', full_name='mancala.QAgent.npits', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nseeds', full_name='mancala.QAgent.nseeds', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Q', full_name='mancala.QAgent.Q', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['QAgent'] = _QAGENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QAgent = _reflection.GeneratedProtocolMessageType('QAgent', (_message.Message,), {
  'DESCRIPTOR' : _QAGENT,
  '__module__' : 'TabularRLData_pb2'
  # @@protoc_insertion_point(class_scope:mancala.QAgent)
  })
_sym_db.RegisterMessage(QAgent)


# @@protoc_insertion_point(module_scope)
